AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LoginS3Name:
    Type: String
  LoginS3Domain:
    Type: String
Resources:
  LoginDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_All
        IPV6Enabled: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Comment: used for shamu-hrs-login
        Origins:
        -
          Id: !Ref LoginS3Name
          DomainName: !Ref LoginS3Domain
          S3OriginConfig:
            OriginAccessIdentity: ''
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref LoginS3Name
          ViewerProtocolPolicy: allow-all


Outputs:
  LoginCloudFrontDomain:
    Value: !GetAtt LoginDistribution.DomainName
