- name: Create config file for company service
  template:
    src: ../templates/config_file_company_template.j2
    dest: ~/hrs/shamu-hrs-company-service/config/application-{{ env }}.yml
- debug:
    msg: "Company service config file created"

- name: Create deploy file for company service
  template:
    src: ../templates/deploy_file_company_template.j2
    dest: ~/hrs/shamu-hrs-company-service/config/deploy.env
- debug:
    msg: "Company service deploy file created"

- name: Create config file for document service
  template:
    src: ../templates/config_file_document_template.j2
    dest: ~/hrs/shamu-hrs-document-service/config/application-{{ env }}.yml
- debug:
    msg: "Document service config file created"

- name: Create deploy file for document service
  template:
    src: ../templates/deploy_file_document_template.j2
    dest: ~/hrs/shamu-hrs-document-service/config/deploy.env
- debug:
    msg: "Document service deploy file created"

- name: Create config file for front-end
  template:
    src: ../templates/config_file_web_template.j2
    dest: ~/hrs/shamu-hrs-web/config/{{ env }}.env
- debug:
    msg: "front-end config file created"

- name: Create deploy file for front-end
  template:
    src: ../templates/deploy_file_web_template.j2
    dest: ~/hrs/shamu-hrs-web/config/deploy.env
- debug:
    msg: "front-end deploy file created"

- name: Create config file for gateway service
  template:
    src: ../templates/config_file_gateway_template.j2
    dest: ~/hrs/shamu-hrs-gateway/src/main/resources/application-{{ env }}.yml
- debug:
    msg: "Gateway service config file created"

- name: Create eb extension config file directory
  file:
    path: ~/hrs/shamu-hrs-gateway/.ebextensions/consul
    state: directory
    mode: 0755
- debug:
    msg: "EB extension config file directory created"

- name: Create eb init config file directory
  file:
    path: ~/hrs/shamu-hrs-gateway/.elasticbeanstalk
    state: directory
    mode: 0755
- debug:
    msg: "EB init config file directory created"

- name: Create eb extention config file for consul
  template:
    src: ../templates/eb_extention_file_template_for_consul.j2
    dest: ~/hrs/shamu-hrs-gateway/.ebextensions/consul/consul-client-install-and-run.config
- debug:
    msg: "EB extension config file for consul created"

- name: Create eb extention config file for nginx
  template:
    src: ../templates/eb_extention_file_template_for_nginx.j2
    dest: ~/hrs/shamu-hrs-gateway/.ebextensions/nginx/conf.d/customConf.conf
- debug:
    msg: "EB extension config file for nginx created"

- name: Create eb init config file for gateway
  template:
    src: ../templates/eb_init_file_template.j2
    dest: ~/hrs/shamu-hrs-gateway/.elasticbeanstalk/config.yml
- debug:
    msg: "EB init config file created"

- name: Create config file for search service
  template:
    src: ../templates/config_file_search_template.j2
    dest: ~/hrs/shamu-hrs-search-service/config/application-{{ env }}.yml
- debug:
    msg: "Search service config file created"

- name: Create deploy file for search service
  template:
    src: ../templates/deploy_file_search_template.j2
    dest: ~/hrs/shamu-hrs-search-service/config/deploy.env
- debug:
    msg: "Search service deploy file created"
