AWSTemplateFormatVersion: 2010-09-09
Parameters:
  StackPrefix:
    Type: String
  Env:
    Type: String

Resources:
  TenantIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${StackPrefix}-${Env}-tenant-preprovision-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - dynamodb.amazonaws.com
                - sqs.amazonaws.com
                - states.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
      Path: /service-role/

Outputs:
  TenantIAMRoleArn:
    Value: !GetAtt TenantIAMRole.Arn

