---

- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  become: 'yes'
  file: >
    path={{ jenkins_home }}/.aws
    state=directory
    owner={{ user }}
    group={{ user }}
    mode=0755

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  become: 'yes'
  template: >
    src=aws_cli_config.j2
    dest={{ jenkins_home }}/.aws/config
    owner={{ user }}
    group={{ user }}
    mode=0600

- name: 'Copy AWS CLI credentials'
  tags: 'aws-cli'
  become: 'yes'
  template: >
    src=aws_cli_credentials.j2
    dest={{ jenkins_home }}/.aws/credentials
    owner={{ user }}
    group={{ user }}
    mode=0600
