AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DeployEnv:
    Type: String
    NoEcho: true
  CompanyRdsUrl:
    Type: String
    NoEcho: true
  DocumentRdsUrl:
    Type: String
    NoEcho: true
  RdsUserName:
    Type: String
    NoEcho: true
  RdsPassword:
    Type: String
    NoEcho: true
  SendGridApiKey:
    Type: String
    NoEcho: true
  Auth0Jwks:
    Type: String
    NoEcho: true
  Auth0Algorithm:
    Type: String
    NoEcho: true
  Auth0Domain:
    Type: String
    NoEcho: true
Resources:
  CompanySecret:
  # creates a secret for company service and stores it in Secrets Manage
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /secret/company-service_${DeployEnv}
      SecretString:
          !Sub '{ ${CompanyRdsUrl}, ${RdsUserName}, ${RdsPassword}, ${SendGridApiKey} }'
  DocumentSecret:
  # creates a secret for document service and stores it in Secrets Manage
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /secret/document-service_${DeployEnv}
      SecretString:
          !Sub '{ ${DocumentRdsUrl}, ${RdsUserName}, ${RdsPassword} }'
  ApplicationSecret:
  # creates a secret for application and stores it in Secrets Manage
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /secret/application_${DeployEnv}
      SecretString:
          !Sub '{ ${Auth0Jwks}, ${Auth0Algorithm}, ${Auth0Domain} }'
Outputs:
  CompanySecretArn:
    Value: !Ref CompanySecret
  DocumentSecretArn:
    Value: !Ref DocumentSecret
  ApplicationSecretArn:
    Value: !Ref ApplicationSecret
